import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import tehamaLogo from '@/assets/tehama-logo.png';

// Company information
const COMPANY_INFO = {
  name: "Tehama Trading Company",
  address: "Sana'a Regional Office",
  footer: {
    postBox: "Post Box: 73",
    location: "Sana'a, Yemen",
    phone: "Phone: 967 1 208916/400266",
    fax: "Fax: 967 1 466056"
  }
};

// Helper function to add header with logo and company info
const addReportHeader = (doc: jsPDF) => {
  // Company info on top-left
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(COMPANY_INFO.name, 14, 15);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(COMPANY_INFO.address, 14, 21);
  
  // Logo on top-right
  try {
    doc.addImage(tehamaLogo, 'PNG', 160, 10, 35, 20);
  } catch (e) {
    console.error('Error adding logo to PDF:', e);
  }
  
  return 30; // Return Y position where content should start
};

// Helper function to add footer
const addReportFooter = (doc: jsPDF, pageNum: number, totalPages: number) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  
  // Center footer with company info
  const footerText = `${COMPANY_INFO.footer.postBox} | ${COMPANY_INFO.footer.location} | ${COMPANY_INFO.footer.phone} | ${COMPANY_INFO.footer.fax}`;
  const textWidth = doc.getTextWidth(footerText);
  const centerX = (doc.internal.pageSize.width - textWidth) / 2;
  doc.text(footerText, centerX, pageHeight - 15);
  
  // Page number
  doc.text(
    `Page ${pageNum} of ${totalPages} - Generated on ${new Date().toLocaleDateString()}`,
    14,
    pageHeight - 10
  );
};

// Helper function to generate report serial number
const generateReportSerialNumber = (reportType: string) => {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const year = String(now.getFullYear()).slice(-2);
  
  // Generate a sequential number based on timestamp (simple approach)
  const counter = String(now.getTime() % 10000).padStart(4, '0');
  
  let prefix = 'RP';
  switch(reportType.toLowerCase()) {
    case 'sales':
      prefix = 'RP-Sales';
      break;
    case 'inventory':
      prefix = 'RP-Inv';
      break;
    case 'purchase orders':
    case 'purchase_orders':
      prefix = 'RP-PO';
      break;
    case 'quotations':
      prefix = 'RP-Quot';
      break;
    default:
      prefix = 'RP-Gen';
  }
  
  return `${prefix}-${counter}-${month}-${year}`;
};

export const generateDetailedQuotationReport = (reportData: {
  title: string;
  dateRange?: string;
  quotations: any[];
  created_by_name?: string;
}) => {
  const doc = new jsPDF();
  
  // Generate report serial number
  const reportSerial = generateReportSerialNumber('quotations');
  
  // Add header with logo and company info
  addReportHeader(doc);
  
  // Report serial number
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report #: ${reportSerial}`, 14, 38);
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(reportData.title, 14, 48);
  
  // Date range if provided
  if (reportData.dateRange) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(reportData.dateRange, 14, 56);
  }
  
  // Created by if provided
  let tableStartY = reportData.dateRange ? 63 : 56;
  if (reportData.created_by_name) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${reportData.created_by_name}`, 14, tableStartY);
    tableStartY += 7;
  }
  
  // Prepare table data
  const tableData = reportData.quotations.map((quotation: any) => {
    // Create items summary
    const itemsSummary = quotation.items.map((item: any) => 
      `${item.name} (${item.quantity})`
    ).join(', ');
    
    // Calculate discount and net amount
    const discountAmount = (quotation.discount_value && quotation.discount_value > 0)
      ? (quotation.discount_type === 'percentage'
        ? (quotation.total_amount * quotation.discount_value / 100)
        : quotation.discount_value)
      : 0;
    const netAmount = quotation.total_amount - discountAmount;
    
    // Discount display
    const discountDisplay = quotation.discount_value && quotation.discount_value > 0
      ? (quotation.discount_type === 'percentage' 
        ? `${quotation.discount_value}%`
        : `$${quotation.discount_value.toFixed(2)}`)
      : '-';
    
    return [
      quotation.quotation_number,
      new Date(quotation.created_at).toLocaleDateString(),
      itemsSummary,
      `$${netAmount.toFixed(2)}`,
      discountDisplay,
      `$${quotation.grand_total.toFixed(2)}`
    ];
  });
  
  // Create table
  autoTable(doc, {
    startY: tableStartY,
    head: [['رقم العرض', 'التاريخ', 'التفاصيل', 'صافي السعر', 'الخصم', 'الإجمالي']],
    body: tableData,
    styles: { 
      fontSize: 8,
      cellPadding: 3,
      halign: 'left'
    },
    headStyles: { 
      fillColor: [63, 81, 181],
      halign: 'center'
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 25 },
      2: { cellWidth: 70 },
      3: { cellWidth: 25 },
      4: { cellWidth: 20 },
      5: { cellWidth: 25 }
    },
    margin: { left: 14, right: 14 }
  });
  
  // Add summary if needed
  const finalY = (doc as any).lastAutoTable.finalY || tableStartY + 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary:', 14, finalY + 10);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Quotations: ${reportData.quotations.length}`, 14, finalY + 17);
  
  const totalGrand = reportData.quotations.reduce((sum, q) => sum + q.grand_total, 0);
  doc.text(`Total Amount: $${totalGrand.toFixed(2)}`, 14, finalY + 24);
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addReportFooter(doc, i, pageCount);
  }
  
  const filename = `${reportSerial}-quotations-report.pdf`;
  doc.save(filename);
};

export const generateReportPDF = (reportData: {
  title: string;
  dateRange?: string;
  headers: string[];
  rows: any[][];
  summary?: { label: string; value: string }[];
  reportType?: string;
  created_by_name?: string;
}) => {
  const doc = new jsPDF();
  
  // Generate report serial number
  const reportSerial = generateReportSerialNumber(reportData.reportType || reportData.title);
  
  // Add header with logo and company info
  addReportHeader(doc);
  
  // Report serial number
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report #: ${reportSerial}`, 14, 38);
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(reportData.title, 14, 48);
  
  // Date range if provided
  if (reportData.dateRange) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(reportData.dateRange, 14, 56);
  }
  
  // Created by if provided
  let tableStartY = reportData.dateRange ? 63 : 56;
  if (reportData.created_by_name) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${reportData.created_by_name}`, 14, tableStartY);
    tableStartY += 7;
  }
  
  // Main table
  autoTable(doc, {
    startY: tableStartY,
    head: [reportData.headers],
    body: reportData.rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [63, 81, 181] }
  });
  
  // Summary section if provided
  if (reportData.summary && reportData.summary.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY || 60;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 14, finalY + 10);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    reportData.summary.forEach((item, index) => {
      doc.text(`${item.label}: ${item.value}`, 14, finalY + 18 + (index * 7));
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addReportFooter(doc, i, pageCount);
  }
  
  const filename = `${reportSerial}-${reportData.title.toLowerCase().replace(/\s+/g, '-')}.pdf`;
  doc.save(filename);
};
