import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import tehamaLogo from '@/assets/tehama-logo.png';

// Company information
const COMPANY_INFO = {
  name: "Tehama Trading Company",
  address: "Sana'a Regional Office",
  footer: {
    postBox: "Post Box: 73",
    location: "Sana'a, Yemen",
    phone: "Phone: 967 1 208916/400266",
    fax: "Fax: 967 1 466056"
  }
};

// Helper function to add header with logo and company info
const addReportHeader = (doc: jsPDF) => {
  // Company info on top-left
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(COMPANY_INFO.name, 14, 15);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(COMPANY_INFO.address, 14, 21);
  
  // Logo on top-right
  try {
    doc.addImage(tehamaLogo, 'PNG', 160, 10, 35, 20);
  } catch (e) {
    console.error('Error adding logo to PDF:', e);
  }
  
  return 30; // Return Y position where content should start
};

// Helper function to add footer
const addReportFooter = (doc: jsPDF, pageNum: number, totalPages: number) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  
  // Center footer with company info
  const footerText = `${COMPANY_INFO.footer.postBox} | ${COMPANY_INFO.footer.location} | ${COMPANY_INFO.footer.phone} | ${COMPANY_INFO.footer.fax}`;
  const textWidth = doc.getTextWidth(footerText);
  const centerX = (doc.internal.pageSize.width - textWidth) / 2;
  doc.text(footerText, centerX, pageHeight - 15);
  
  // Page number
  doc.text(
    `Page ${pageNum} of ${totalPages} - Generated on ${new Date().toLocaleDateString()}`,
    14,
    pageHeight - 10
  );
};

// Helper function to generate report serial number
const generateReportSerialNumber = (reportType: string) => {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const year = String(now.getFullYear()).slice(-2);
  
  // Generate a sequential number based on timestamp (simple approach)
  const counter = String(now.getTime() % 10000).padStart(4, '0');
  
  let prefix = 'RP';
  switch(reportType.toLowerCase()) {
    case 'sales':
      prefix = 'RP-Sales';
      break;
    case 'inventory':
      prefix = 'RP-Inv';
      break;
    case 'purchase orders':
    case 'purchase_orders':
      prefix = 'RP-PO';
      break;
    case 'quotations':
      prefix = 'RP-Quot';
      break;
    default:
      prefix = 'RP-Gen';
  }
  
  return `${prefix}-${counter}-${month}-${year}`;
};

export const generateDetailedQuotationReport = (reportData: {
  title: string;
  dateRange?: string;
  quotations: any[];
  created_by_name?: string;
}) => {
  const doc = new jsPDF();
  
  // Generate report serial number
  const reportSerial = generateReportSerialNumber('quotations');
  
  // Add header with logo and company info
  addReportHeader(doc);
  
  // Report serial number
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report #: ${reportSerial}`, 14, 38);
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(reportData.title, 14, 48);
  
  // Date range if provided
  if (reportData.dateRange) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(reportData.dateRange, 14, 56);
  }
  
  // Created by if provided
  let currentY = reportData.dateRange ? 63 : 56;
  if (reportData.created_by_name) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${reportData.created_by_name}`, 14, currentY);
    currentY += 10;
  }
  
  // Process each quotation
  reportData.quotations.forEach((quotation, index) => {
    // Start a new page for each quotation after the first to avoid overlap
    if (index > 0) {
      doc.addPage();
      addReportHeader(doc);
      currentY = 40;
    }
    // Check if we need a new page
    if (currentY > 240) {
      doc.addPage();
      addReportHeader(doc);
      currentY = 40;
    }
    
    // Quotation header
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Quotation #: ${quotation.quotation_number}`, 14, currentY);
    currentY += 6;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date(quotation.created_at).toLocaleDateString()}`, 14, currentY);
    doc.text(`Customer: ${quotation.customer_name}`, 100, currentY);
    currentY += 8;
    
    // Items table
    const itemsData = quotation.items.map((item: any) => [
      item.name,
      item.quantity.toString(),
      `$${item.unit_price.toFixed(2)}`,
      `$${item.total_price.toFixed(2)}`
    ]);
    
    autoTable(doc, {
      startY: currentY,
      head: [['Item', 'Qty', 'Unit Price', 'Total']],
      body: itemsData,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [63, 81, 181] },
      margin: { left: 14, right: 14 }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 5;
    
    // Financial summary
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    // Calculate discount if exists
    if (quotation.discount_value && quotation.discount_value > 0) {
      const discountAmount = quotation.discount_type === 'percentage'
        ? (quotation.total_amount * quotation.discount_value / 100)
        : quotation.discount_value;
      const discountLabel = quotation.discount_type === 'percentage'
        ? `Given Discount (${quotation.discount_value}%):`
        : 'Given Discount:';
      
      doc.text(discountLabel, 130, currentY);
      doc.text(`-$${discountAmount.toFixed(2)}`, 180, currentY, { align: 'right' });
      currentY += 5;
      
      const netAmount = quotation.total_amount - discountAmount;
      doc.text('Net Amount:', 130, currentY);
      doc.text(`$${netAmount.toFixed(2)}`, 180, currentY, { align: 'right' });
      currentY += 5;
    }
    
    doc.text('Tax & Customs:', 130, currentY);
    doc.text(`$${quotation.tax_amount.toFixed(2)}`, 180, currentY, { align: 'right' });
    currentY += 5;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Grand Total:', 130, currentY);
    doc.text(`$${quotation.grand_total.toFixed(2)}`, 180, currentY, { align: 'right' });
    currentY += 10;
    
    // Separator line
    if (index < reportData.quotations.length - 1) {
      doc.setDrawColor(200, 200, 200);
      doc.line(14, currentY, 196, currentY);
      currentY += 10;
    }
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addReportFooter(doc, i, pageCount);
  }
  
  const filename = `${reportSerial}-detailed-quotations-report.pdf`;
  doc.save(filename);
};

export const generateReportPDF = (reportData: {
  title: string;
  dateRange?: string;
  headers: string[];
  rows: any[][];
  summary?: { label: string; value: string }[];
  reportType?: string;
  created_by_name?: string;
}) => {
  const doc = new jsPDF();
  
  // Generate report serial number
  const reportSerial = generateReportSerialNumber(reportData.reportType || reportData.title);
  
  // Add header with logo and company info
  addReportHeader(doc);
  
  // Report serial number
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report #: ${reportSerial}`, 14, 38);
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(reportData.title, 14, 48);
  
  // Date range if provided
  if (reportData.dateRange) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(reportData.dateRange, 14, 56);
  }
  
  // Created by if provided
  let tableStartY = reportData.dateRange ? 63 : 56;
  if (reportData.created_by_name) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${reportData.created_by_name}`, 14, tableStartY);
    tableStartY += 7;
  }
  
  // Main table
  autoTable(doc, {
    startY: tableStartY,
    head: [reportData.headers],
    body: reportData.rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [63, 81, 181] }
  });
  
  // Summary section if provided
  if (reportData.summary && reportData.summary.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY || 60;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 14, finalY + 10);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    reportData.summary.forEach((item, index) => {
      doc.text(`${item.label}: ${item.value}`, 14, finalY + 18 + (index * 7));
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addReportFooter(doc, i, pageCount);
  }
  
  const filename = `${reportSerial}-${reportData.title.toLowerCase().replace(/\s+/g, '-')}.pdf`;
  doc.save(filename);
};
